### ISSUE TITLE
Require a fix name / error code

### ISSUE THREAD

**Issue by andrewbranch** [iisaduan/TS-transform-project#15]
I think we should do away with the default of applying all available fixes. It’s bound to produce a ton of undesired changes.

**Comment by iisaduan** [comment]
Currently, behavior is fixes are only applied if at least one of `errorCode` or `fixName` is supplied. Otherwise process exits with warning.  https://github.com/iisaduan/ts-fix/commit/26bb5c6c899658a60021b82e01b2e3fbe54b300b
